[package]
name = "cli-select"
version = "0.1.0"
authors = ["Santiago Verdu <santiago_verdu@byu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
